# Carga de Dados com Insert


# Limpa a tabela
TRUNCATE cap10.TB_CLIENTE;

# Carrega os dados em TB_CLIENTE
INSERT INTO cap10.TB_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('A10984EDCF10092', 'Bob Marley', 'Rio de Janeiro', '1', '72132900');

INSERT INTO cap10.TB_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('B10984EDCF10093', 'Elvis Presley', 'Rio de Janeiro', '1', '62132900');

INSERT INTO cap10.TB_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('C10984EDCF10094', 'Chuck Berry', 'Fortaleza', '0', '65132900');

INSERT INTO cap10.TB_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('D10984EDCF10095', 'James Brown', 'Porto Alegre', '0', '82132900');

INSERT INTO cap10.TB_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('E10984EDCF10096', 'Aretha Franklin', 'Natal', '1', '22132900');

INSERT INTO cap10.TB_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('F10984EDCF10097', 'Ray Charles', 'Fortaleza', '1', '67332900');

INSERT INTO cap10.TB_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('G10984EDCF10098', 'Marvin Gaye', 'Natal', '1', '12132900');

INSERT INTO cap10.TB_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('H10984EDCF10099', 'Bruce Springsteen', 'Porto Alegre', '0', '42132900');

INSERT INTO cap10.TB_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('I10984EDCF10100', 'Neil Young', 'Rio de Janeiro', '1', '92132900');

INSERT INTO cap10.TB_CLIENTE (NK_ID_CLIENTE, NM_CLIENTE, NM_CIDADE_CLIENTE, BY_ACEITA_CAMPANHA, DESC_CEP) 
VALUES ('J10984EDCF10101', 'John Lennon', 'Rio de Janeiro', '1', '72132900');


# Limpa a tabela
TRUNCATE cap10.TB_LOCALIDADE;

# Carrega os dados em TB_LOCALIDADE
INSERT INTO cap10.TB_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1001', 'Loja A', 'Rio de Janeiro', 'Sudeste');

INSERT INTO cap10.TB_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1002', 'Ponto de Venda X', 'Rio de Janeiro', 'Sudeste');

INSERT INTO cap10.TB_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1003', 'Loja B', 'Fortaleza', 'Nordeste');

INSERT INTO cap10.TB_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1004', 'Loja C', 'Porto Alegre', 'Sul');

INSERT INTO cap10.TB_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1005', 'Loja D', 'Porto Alegre', 'Sul');

INSERT INTO cap10.TB_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1006', 'Loja H', 'Natal', 'Nordeste');

INSERT INTO cap10.TB_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1007', 'Ponto de Venda Y', 'Porto Alegre', 'Sul');

INSERT INTO cap10.TB_LOCALIDADE (NK_ID_LOCALIDADE, NM_LOCALIDADE, NM_CIDADE_LOCALIDADE, NM_REGIAO_LOCALIDADE) 
VALUES ('1008', 'Loja K', 'Rio de Janeiro', 'Sudeste');


# Limpa a tabela
TRUNCATE cap10.TB_PRODUTO;

# Carrega os dados em TB_PRODUTO
INSERT INTO cap10.TB_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098712', 'DFGTHN6ER4RF', 'Iphone 13', 'Smartphone', 'Apple');

INSERT INTO cap10.TB_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098713', 'RFGTHN6ER4RF', 'Iphone 12', 'Smartphone', 'Apple');

INSERT INTO cap10.TB_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098714', 'TFGTHN6ER4RF', 'Notebook 16 GB', 'Notebook', 'Asus');

INSERT INTO cap10.TB_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098715', 'HFGTHN6ER4RF', 'Camera 80 MM', 'Camera', 'Sony');

INSERT INTO cap10.TB_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098716', 'SFGTHN6ER4RF', 'Ipad Mini', 'Tablet', 'Apple');

INSERT INTO cap10.TB_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098717', 'MFGTHN6ER4RF', 'Camera 90 MM', 'Camera', 'Canon');

INSERT INTO cap10.TB_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098718', 'NFGTHN6ER4RF', 'Impressora Colorida', 'Impressora', 'Epson');

INSERT INTO cap10.TB_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098719', 'BFGTHN6ER4RF', 'Impressora InkJet', 'Impressora', 'Epson');

INSERT INTO cap10.TB_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098710', 'CFGTHN6ER4RF', 'HD Externo SSD 1 TB', 'Perifericos', 'Samsung');

INSERT INTO cap10.TB_PRODUTO (NK_ID_PRODUTO, DESC_SKU, NM_PRODUTO, NM_CATEGORIA_PRODUTO, NM_MARCA_PRODUTO) 
VALUES ('12098711', 'UFGTHN6ER4RF', 'HD Externo HDD 2 TB', 'Perifericos', 'Samsung');

